// src/web/react/userstate/userstate.tsx
import * as React from 'react';

import { ICoreState } from '../../../core-state/core.state';
import { actionTrigger$, actionType } from '../../../core-state/core.store';
import { IUserstateCollection } from '../../../core-state/userstate-collection.interface';
import {
  userstateActionType,
  UserstateCollectionUpdateAction,
} from '../../../core-state/userstates.reducer';

import { connect } from '../util/connect';

interface IState {
  userstateColls: ReadonlyArray<IUserstateCollection>;
  item: IUserstateCollection;
}

interface ICmpProps extends IState {
  action: (u: actionType) => void;
}

const cmp: React.SFC<ICmpProps> = ({ userstateColls, item, action }) => (
  <div>
    <textarea
      rows={5}
      value={JSON.stringify(item)}
      onBlur={e =>
        action(
          new UserstateCollectionUpdateAction(
            userstateColls,
            item,
            JSON.parse(e.currentTarget.value)
          )
        )
      }
    />
  </div>
);

export default (selector: (s: ICoreState) => IState) => connect(selector, actionTrigger$)(cmp);

// src/web/userstate/userstate.tsx
import { Subject } from 'rxjs/Subject';
import { FunctionalComponentOptions, VNode, VNodeData } from 'vue';

import { IUserstateCollection } from '../../core-state/userstate-collection.interface';
import { userstateActionType, UserstateCollectionUpdateAction } from '../../core-state/userstates.reducer';

const cmp: FunctionalComponentOptions<Record<string, any>, string[]> = {
  functional: true,
  render(h, a): VNode {
    const data: VNodeData & {
      userstateColls: ReadonlyArray<IUserstateCollection>;
      userstate: IUserstateCollection;
      actionTrigger$: Subject<userstateActionType>;
    } = a.data as any;
    const actionTrigger$ = data.actionTrigger$;
    return (
      <div>
        <textarea
          rows="5"
          value={JSON.stringify(data.userstate)}
          onBlur={e =>
            actionTrigger$.next(
              new UserstateCollectionUpdateAction(data.userstateColls, data.userstate, JSON.parse(e.target.value))
            )
          }
        />
      </div>
    );
  },
};

export const stUserstate = { name: 'st-userstate', cmp };
