// src/web/react/query/time-duration.tsx
import { ITimeDuration } from '@autoschedule/queries-fn';
import * as React from 'react';

import { displayFlex, flexGrow } from '../shared/style.css';

import { parseValue } from './util';

interface ICmpProps {
  timeDuration: ITimeDuration | undefined;
  actionFn: (a: ITimeDuration | undefined) => void;
}

const cmp: React.SFC<ICmpProps> = ({ actionFn, timeDuration, children }) => (
  <div className={displayFlex}>
    <div>{children}</div>
    <textarea
      className={flexGrow(1)}
      rows={1}
      defaultValue={JSON.stringify(timeDuration)}
      key={valueToString(timeDuration)}
      onBlur={e => actionFn(parseValue(e.currentTarget.value))}
    />
    <button onClick={() => actionFn({ ...defaultValue })}>default</button>
  </div>
);

export default cmp;

const defaultValue: ITimeDuration = { min: 1, target: 1 };

const valueToString = (v: ITimeDuration | undefined) => {
  return v ? `${v.min}-${v.target}` : '--';
}

// src/web/vue/query/time-duration.tsx
import { ITimeDuration } from '@autoschedule/queries-fn';
import { FunctionalComponentOptions, VNode } from 'vue';

import { displayFlex, flexGrow } from '../shared/style.css';

import { parseValue } from './util';

interface ICmpProps {
  timeDuration: ITimeDuration;
  actionFn: (a: ITimeDuration) => void;
}

const cmp: FunctionalComponentOptions<ICmpProps, string[]> = {
  functional: true,
  render(h, a): VNode {
    return (
      <div class={displayFlex}>
        <div>{a.slots().default}</div>
        <textarea
          class={flexGrow(1)}
          rows="1"
          value={JSON.stringify(a.props.timeDuration)}
          onBlur={e => a.props.actionFn(parseValue(e.target.value))}
        />
        <button onClick={() => a.props.actionFn({...defaultValue})}>default</button>
      </div>
    );
  },
};

const defaultValue: ITimeDuration = { min: 1, target: 1 };

export const stTimeDuration = { name: 'st-time-duration', cmp };
